### ISSUE TITLE
https://github.com/FIWARE/node-red-contrib-FIWARE_official is not deprecated is new!

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/awesome#1]

**Comment by jason-fox** [comment]
To move forward just fork the repo and open a PR to add something to the list or move it to the right section. Its very early days and only the top half of the list is properly formatted and in the right location so please follow  the style of that section as a guideline.

Thanks.

**Comment by jason-fox** [comment]
Fixed  d4f3e88
