### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by ghost** [FIWARE/awesome#2]
Hi, Jason sorry that I am contacting you via issue I failed to find your email, we talked on fiware community meeting regarding how to add to this list I was representing NgsiConnectorTools. Do you have any information on how to move forward with this list and what is expected from us? You can contact me via email igor.despot@eng.it and remove this issue since it is more question that problem.
Thanks.

**Comment by jason-fox** [comment]
To move forward just fork the repo and open a PR to add something to the list. Its very early days and only the top half of the list is properly formatted, so please follow that section as a guideline.

Thanks.

**Comment by MarijaBorisov** [comment]
Dear Jason, 
Do you have any news about our PR? 
Should we make some additional changes in order for our tool to be included in the list?
Please let us know if anything is needed.

Sorry for contacting you this way.
Thank you.
Best regards,
Marija Borisov

**Comment by jason-fox** [comment]
Thanks for the reminder. I've somehow missed the PR request over the holidays.

Now Merged - Fixed by #3
